### ISSUE TITLE
Investigate 404 error in console

### ISSUE THREAD

**Issue by rnewstead1** [rnewstead1/nevis-wedding#1]
This keeps occurring:

```
GET /js/rsvp-form.js 304 2.651 ms - -
GET /js/es6-promise.map 404 4.529 ms - 1104
Error: Not Found
    at app.use (/Users/rachel/code/nevis-range/src/app/routes.js:44:17)
    at Layer.handle [as handle_request] (/Users/rachel/code/nevis-range/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:312:13)
    at /Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:271:10)
    at /Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:618:15
    at next (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/rachel/code/nevis-range/node_modules/express/lib/router/index.js:46:12)
```

Doesn't seem to be causing any problems though...

**Comment by will-normand** [comment]
This happens in Chrome but not Firefox.

**Comment by will-normand** [comment]
The chrome debugger seems to be requesting this file to map from obfuscated js back to the original source.  But es6-promise.map is in the node_module, not our js directory.
