### ISSUE TITLE
Handle invalid email addresses

### ISSUE THREAD

**Issue by rnewstead1** [rnewstead1/nevis-wedding#14]
At the moment, the form submit fails silently (with a 500) in this instance and we get the following error in the logs:
```bash
Something went wrong submitting rsvp details { Error: No recipients defined
    at SMTPConnection._formatError (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._setEnvelope (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:719:30)
    at SMTPConnection.send (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:383:10)
    at SMTPTransport.<anonymous> (/Users/rachel/code/nevis-range/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:126:24)
    at /Users/rachel/code/nevis-range/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:162:21
    at SMTPConnection._actionAUTHComplete (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:1236:5)
    at SMTPConnection.<anonymous> (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:319:22)
    at SMTPConnection._processResponse (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData (/Users/rachel/code/nevis-range/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:96:13) code: 'EENVELOPE', command: 'API' }
PUT /api/rsvp 500 314.517 ms - 21
```
If you then try to press the submit button again, it doesn't seem to submit at all.

The above was produced by typing 'Rachel' in the email box.

**Comment by rnewstead1** [comment]
email regex: `/^\S+@\S+\.[A-Za-z0-9-]{2,}$/`

**Comment by will-normand** [comment]
Just changed the input type to "email".
